# Do NOT remove or touch this
config-version: 1

# Enables or disables the automatic datapack downloader
# This can be used to prevent overriding changes when testing
pack-downloader: false

settings:
  # This unbinds /reload from reloading cocktail
  unbind-reload: false
  # Page length of reports
  # Warning: this setting isn't well tested, expect bugs and errors
  report-page-length: 5

datapack-urls:
  datapack-name-here:
    # Make sure the link either redirects to a download page or is a direct link to a zip of the pack
    url: "https://put-your-page.here/"
