# Do NOT remove or touch this
config-version: 3

# Enables or disables the automatic datapack downloader
# This can be used to prevent overriding changes when testing
pack-downloader: true

# This unbinds /reload from reloading cocktail
unbind-reload: false

resource-pack-server:
  # Enable resource pack server, this is required to send resource packs from datapacks to players
  enabled: true

  # Sets the port to put this on, make sure to run this on an open port
  # It may require opening a separate port for this to work
  port: 8080

  # Set which resource pack to use
  active-resource-pack: "datapack-name-here" # this is the name of the entry in datapack-urls

datapack-urls:
  datapack-name-here:
    # Make sure the link either redirects to a download page or is a direct link to a zip of the pack
    url: "https://put-your-page.here/"
